---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  asciicast_theme = "readme"
)

asciicast::init_knitr_engine()
```

# trngl

<!-- badges: start -->
<!-- badges: end -->

trngl provides simulation-based tools for checking the assumptions of actuarial reserving models.

## Installation


``` r
install.packages("trngl")

# To get the development version from GitHub:
# install.packages("remotes")
remotes::install_github("oelhammouchi/trngl@develop")
```

## Example

Flag a suspicious point:

```{asciicast}
#' End_wait: 5
#' At: all

library(trngl)

triangle <- cum2incr(UKMotor)
triangle[1, 4] <- 10 * triangle[1, 4]
triangle <- incr2cum(triangle)
res <- odpParamSim(triangle, "single",
  dist = "gamma",
  n_boot = 1e2,
  n_sim = 1e2,
  progress = TRUE
)

print(triangle)
```

Inspect the simulation results:

```{asciicast}
#' End_wait: 5
#' At: all

print(res)
```

```{r include=FALSE, echo=FALSE}
library(trngl)

triangle <- cum2incr(UKMotor)
triangle[1, 4] <- 10 * triangle[1, 4]
triangle <- incr2cum(triangle)
res <- odpParamSim(triangle, "single",
  dist = "gamma",
  n_boot = 1e2,
  n_sim = 1e2,
  progress = FALSE
)
```

```{r plot, dpi=300}
plot(res)
```

