# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' trngl configuration functions
#'
#' trngl uses an internal threadsafe random number generator. These
#' functions can be used to configure it.
#'
#' @param n_threads Number of threads to use
#' @param seed Seed for the random number generator
#' @name config
#' @export
setTrnglThreads <- function(n_threads) {
    invisible(.Call('_trngl_setTrnglThreads', PACKAGE = 'trngl', n_threads))
}

#' @rdname config
#' @export
getTrnglThreads <- function() {
    .Call('_trngl_getTrnglThreads', PACKAGE = 'trngl')
}

#' @rdname config
#' @export
setTrnglSeed <- function(seed) {
    invisible(.Call('_trngl_setTrnglSeed', PACKAGE = 'trngl', seed))
}

#' @rdname config
#' @export
getTrnglSeed <- function() {
    .Call('_trngl_getTrnglSeed', PACKAGE = 'trngl')
}

#' @export
.mackParamBoot <- function(trngl, dist, cond, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_trngl_mackParamBoot', PACKAGE = 'trngl', trngl, dist, cond, n_boot, n_sim, progress)
}

#' @export
.mackResidBoot <- function(trngl, resid_type, cond, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_trngl_mackResidBoot', PACKAGE = 'trngl', trngl, resid_type, cond, n_boot, n_sim, progress)
}

#' @export
.mackPairsBoot <- function(trngl, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_trngl_mackPairsBoot', PACKAGE = 'trngl', trngl, n_boot, n_sim, progress)
}

#' @export
.mackPairsSim <- function(trngl, sim_type, n_boot, n_sim, progress) {
    .Call('_trngl_mackPairsSim', PACKAGE = 'trngl', trngl, sim_type, n_boot, n_sim, progress)
}

#' @export
.mackParamSim <- function(trngl, sim_type, cond, dist, n_boot, n_sim, progress) {
    .Call('_trngl_mackParamSim', PACKAGE = 'trngl', trngl, sim_type, cond, dist, n_boot, n_sim, progress)
}

#' @export
.mackResidSim <- function(trngl, sim_type, cond, resid_type, n_boot, n_sim, progress) {
    .Call('_trngl_mackResidSim', PACKAGE = 'trngl', trngl, sim_type, cond, resid_type, n_boot, n_sim, progress)
}

.odpParamBoot <- function(trngl, dist, n_boot, n_sim, progress) {
    .Call('_trngl_odpParamBoot', PACKAGE = 'trngl', trngl, dist, n_boot, n_sim, progress)
}

.odpResidBoot <- function(trngl, n_boot, n_sim, progress) {
    .Call('_trngl_odpResidBoot', PACKAGE = 'trngl', trngl, n_boot, n_sim, progress)
}

.odpParamSim <- function(trngl, sim_type, dist, n_boot, n_sim, progress) {
    .Call('_trngl_odpParamSim', PACKAGE = 'trngl', trngl, sim_type, dist, n_boot, n_sim, progress)
}

.odpResidSim <- function(trngl, sim_type, n_boot, n_sim, progress) {
    .Call('_trngl_odpResidSim', PACKAGE = 'trngl', trngl, sim_type, n_boot, n_sim, progress)
}

