# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
setCBThreads <- function(n_threads) {
    invisible(.Call('_claimsBoot_setCBThreads', PACKAGE = 'claimsBoot', n_threads))
}

#' @export
getCBThreads <- function() {
    .Call('_claimsBoot_getCBThreads', PACKAGE = 'claimsBoot')
}

#' @export
setCBSeed <- function(seed) {
    invisible(.Call('_claimsBoot_setCBSeed', PACKAGE = 'claimsBoot', seed))
}

#' @export
getCBSeed <- function() {
    .Call('_claimsBoot_getCBSeed', PACKAGE = 'claimsBoot')
}

#' @export
.mackParamBoot <- function(trngl, dist, cond, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_claimsBoot_mackParamBoot', PACKAGE = 'claimsBoot', trngl, dist, cond, n_boot, n_sim, progress)
}

#' @export
.mackResidBoot <- function(trngl, resid_type, cond, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_claimsBoot_mackResidBoot', PACKAGE = 'claimsBoot', trngl, resid_type, cond, n_boot, n_sim, progress)
}

#' @export
.mackPairsBoot <- function(trngl, n_boot = 1e3L, n_sim = 1e3L, progress = TRUE) {
    .Call('_claimsBoot_mackPairsBoot', PACKAGE = 'claimsBoot', trngl, n_boot, n_sim, progress)
}

#' @export
.mackPairsSim <- function(trngl, sim_type, n_boot, n_sim, progress) {
    .Call('_claimsBoot_mackPairsSim', PACKAGE = 'claimsBoot', trngl, sim_type, n_boot, n_sim, progress)
}

#' @export
.mackParamSim <- function(trngl, sim_type, cond, dist, n_boot, n_sim, progress) {
    .Call('_claimsBoot_mackParamSim', PACKAGE = 'claimsBoot', trngl, sim_type, cond, dist, n_boot, n_sim, progress)
}

#' @export
.mackResidSim <- function(trngl, sim_type, cond, resid_type, n_boot, n_sim, progress) {
    .Call('_claimsBoot_mackResidSim', PACKAGE = 'claimsBoot', trngl, sim_type, cond, resid_type, n_boot, n_sim, progress)
}

#' @export
.odpParamBoot <- function(trngl, dist, n_boot, n_sim, progress) {
    .Call('_claimsBoot_odpParamBoot', PACKAGE = 'claimsBoot', trngl, dist, n_boot, n_sim, progress)
}

#' @export
.odpResidBoot <- function(trngl, n_boot, n_sim, progress) {
    .Call('_claimsBoot_odpResidBoot', PACKAGE = 'claimsBoot', trngl, n_boot, n_sim, progress)
}

#' @export
.odpParamSim <- function(trngl, sim_type, dist, n_boot, n_sim, progress) {
    .Call('_claimsBoot_odpParamSim', PACKAGE = 'claimsBoot', trngl, sim_type, dist, n_boot, n_sim, progress)
}

#' @export
.odpResidSim <- function(trngl, sim_type, n_boot, n_sim, progress) {
    .Call('_claimsBoot_odpResidSim', PACKAGE = 'claimsBoot', trngl, sim_type, n_boot, n_sim, progress)
}

#' @export
glm_fit_test <- function(triangle) {
    .Call('_claimsBoot_glm_fit_test', PACKAGE = 'claimsBoot', triangle)
}

